server:
  port: 8080
spring:
  application:
    name: api-gateway
  security:
    oauth2:
      client:
        provider:
          spring:
            issuer-uri: http://localhost:8088
        registration:
          reg-client:
            provider: spring
            client-id: client
            client-secret: "secret"
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: http://127.0.0.1:8080/login/oauth2/code/reg-client
            scope: openid, profile
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: user-service
          uri: http://localhost:8000
          predicates:
            - Path=/user/**
          filters:
            - TokenRelay=

logging:
  level:
    org:
      springframework:
        security: debug
