server:
  port: 8090

#Datasource
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/moneyaccountdatabase
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Satgaino1@

#Jpa
  jpa:
    hibernate:
      ddl-auto: update

#Kafka

  kafka:
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      properties:
#        spring:
#          json:
#            trusted:
#              packages: "*"

#Cloud

#Circuit Breaker
#CHECK_EXISTING_USER_BREAKER
resilience4j:
  circuitbreaker:
    instances:
      CHECK_EXISTING_USER_BREAKER:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 5000
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
#Jeager
tracing:
  url: http://localhost:4318/v1/traces

management:
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: "%5p [${spring.application.name:}, %X{traceId:-}, %X{spanId:-}]"
