spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tuanvo1603/CurrencyAndAccountServiceConfig.git
          repos:
            currency-and-account-service:
              uri: https://github.com/tuanvo1603/CurrencyAndAccountServiceConfig.git
  profiles:
    default: default
server:
  port: 9005